setono_sylius_navigation_admin_navigation:
    resource: |
        section: admin
        alias: setono_sylius_navigation.navigation
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: update
        grid: setono_sylius_navigation_admin_navigation
        vars:
            all:
                subheader: setono_sylius_navigation.ui.manage_navigations
                templates:
                    form: "@SetonoSyliusNavigationPlugin/navigation/_form.html.twig"
            index:
                icon: 'align justify'
    type: sylius.resource

setono_sylius_navigation_admin_navigation_build_from_taxon:
    path: /navigations/{id}/build-from-taxon
    methods: [ GET,POST ]
    controller: Setono\SyliusNavigationPlugin\Controller\BuildFromTaxonController
    requirements:
        id: ^\d+$
